language: node_js
node_js:
#  - "6"
#  - "8"
#  - "10"
   - "12"
   - "14"
install:
  - npm install -g codecov nyc mocha ts-node typescript
  - npm install -D
cache:
  directories:
    - node_modules
script:
  - npm run report
after_success:
  - codecov