name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        # Use PAT instead of default Github token, because the default
        # token deliberately will not trigger another workflow run
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      # Skip post-install to avoid malicious scripts stealing PAT
      run: npm ci --legacy-peer-deps
    - name: Test
      run: npm test
    - name: Tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: ./tag.sh
